name: br_utils
description: Utils library for specific Brazilian businesses
version: 0.0.1
homepage: https://github.com/henriquenas/br_utils
repository: https://github.com/henriquenas/br_utils
issue_tracker: https://github.com/henriquenas/br_utils/issues
documentation: https://pub.dev/packages/br_utils

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0
